spring:
  application:
    name: ideognostic-diagnosis-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://config-server:8070"

servlet:
  multipart:
    enabled: true # Enable multipart support
    max-file-size: 10MB # Maximum file size allowed
    max-request-size: 10MB # Maximum request size (multiple files)

