server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: verbal-diagnosis-service
          uri: lb://verbal-diagnosis-service
          predicates:
            - Path=/api/v1/verbal/**
        - id: lexical-diagnosis-service
          uri: lb://lexical-diagnosis-service
          predicates:
            - Path=/api/v1/lexical/**
        - id: operational-diagnosis-service
          uri: lb://operational-diagnosis-service
          predicates:
            - Path=/api/v1/operational/**
        - id: ideognostic-diagnosis-service
          uri: lb://ideognostic-diagnosis-service
          predicates:
            - Path=/api/v1/ideognostic/**
        - id: sequential-diagnosis-service
          uri: lb://sequential-diagnosis-service
          predicates:
            - Path=/api/v1/sequential/**
        - id: visual-diagnosis-service
          uri: lb://visual-diagnosis-service
          predicates:
            - Path=/api/v1/visual/**
        - id: practognostic-diagnosis-service
          uri: lb://practognostic-diagnosis-service
          predicates:
            - Path=/api/v1/practognostic/**
        - id: graphical-diagnosis-service
          uri: lb://graphical-diagnosis-service
          predicates:
            - Path=/api/v1/graphical/**
        - id: iq-test-service
          uri: lb://iq-test-service
          predicates:
            - Path=/api/v1/iq/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0