server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/v1/user/**
          - id: verbal-diagnosis-service
            uri: lb://verbal-service
            predicates:
              - Path=/api/v1/verbal/**
          - id: lexical-diagnosis-service
            uri: lb://lexical-service
            predicates:
              - Path=/api/v1/lexical/**
          - id: sequential-diagnosis-service
            uri: lb://sequential-service
            predicates:
              - Path=/api/v1/sequential/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0