name: Build and Deploy CalcPal Mobile Backend Application

on:
  pull_request:
    branches: [main]
  
  push:
    branches: [development]

jobs:
  cd-pipeline:
    name: Build and Deploy CalcPal Mobile Backend Application
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - service-registry
          - config-server
          - api-gateway
          - user-service
          - verbal-diagnosis-service
          - lexical-diagnosis-service
          - ideognostic-diagnosis-service
          - operational-diagnosis-service
          - sequential-diagnosis-service
          - visual-diagnosis-service
          - practognostic-diagnosis-service
          - graphical-diagnosis-service

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Set up Environment Variables
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
          MAIL_APP_PASSWORD: ${{ secrets.MAIL_APP_PASSWORD }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: bash setup_env.sh

      - name: Run Unit Tests for ${{ matrix.service }}
        run: mvn -B test --file ${{ matrix.service }}/pom.xml

      - name: Build the Application for ${{ matrix.service }}
        run: mvn -B package --file ${{ matrix.service }}/pom.xml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image for ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/calcpal-${{ matrix.service }}:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/calcpal-${{ matrix.service }}:latest
